### PR TITLE
Moodle 4.5 branch

### PR DESCRIPTION
**Pull request by Syxton**

### CODE REVIEW

**Comment by PhMemmel** [comment]
@Syxton Thanks for the work! I had a quick look.

Your patch fixes the basic issue, great!

However, I would suggest to make the three dropdowns resemble the current course structure by moving the subsections to the "correct" place and also add a small indentation or a small symbol as prefix to the name to them. What do you think?

**Review by PhMemmel — CHANGES_REQUESTED** [review]
This looks like a very good implementation, great!

Just 2 things:
- Updating a section name for example will fill up the section list dropdown with duplicate entries. I suggest to add `sections = [];` before line 97
- I'm not sure what the users would expect: By selecting a section only the course modules in a section will be selected, but not the course modules inside the subsections. Is this intended? Or would a user expect to select all course modules including the course modules in the subsections of the section he selected?

**Comment by Syxton** [comment]
@PhMemmel Thank you for looking through it.  I have made the requested changes.  I think we could look into creating those fancy new menus like Moodle uses for groups and availability that could allow selecting each section individually but also have a button for selecting all subsections as well.  For now we'll keep it as is because we can select by section but can't subtract selections by section.  It would be a bit faster to select everything in a section and its subsections, but would be very slow to select all in a section and its subsections then deselect everything it each subsection module by module if you only wanted the outer sections modules.

**Comment by PhMemmel** [comment]
Alright.

I just discovered one maybe minor issue:

- Enable moodle mass actions
- Click on the checkbox of a section
- You then will not be able to select a course module inside this section
- However, you will still be able to select course modules inside this section by using our "select" dropdown.

Do you consider this as a problem? I mean... they are still selected, the checkboxes are just greyed out, but the checks are there, and applying an action also works :) We just break how the moodle mass actions work.

**Comment by Syxton** [comment]
@PhMemmel Hmm.  While it isn't necessarily ideal with how it looks, Seems to me that this functionality might offer a more expected behavior than if block mass action selection being ignored if a section was selected by accident.  However, we could clear any section selection upon using mass action selection so that they don't overlap, much like Moodle clears the checkboxes of the modules when the section is selected.  What do you think?

**Comment by PhMemmel** [comment]
I'm fine with how it currently behaves. So let's go with it. Testing is fine, CR too, so feel free to merge if you do not have any other issues with moodle 4.5 compatibility you want/need to address.

**Comment by Syxton** [comment]
@PhMemmel Agreed, it is a little more complicated than I thought anyway.  If you select an individual activity, Moodle disables the section checkbox, but if we select the activities using mass actions block, we don't disable the section check boxes.  seems better to just let there be a visual discrepancy but allow both tools to just work.

**Pull request merged**
