### PR TITLE
Modularize tests

### PR DESCRIPTION
**Pull request by Syxton**
I have included tests for all formats we have dealt with in the past. The tests can't pass until the formats are supported and the Mass Actions block is allowed to be added. So currently supported (in code at least), are core, topcoll, tiles, onetopic. seems that grid is in a similar spot for 4.0 compliance. Flexsections isn't too far out, but it does break Moodle in its current form. I will push the changes I made to see if I can jump start that format.

core passes all tests pass (1 skip is expected to test the "format is not installed" test)
topcoll latest passes all tests and should be supported.
grid needs updated to remove deprecated functions and implement indent, but our tests for it are probably correct. With all warnings hidden, mass actions will work except for indent. Could be supported.
tiles needs updated to remove deprecated functions and implement indent, but our tests for it are probably correct. With all warnings hidden, mass actions will work except for indent. Could be supported.
onetopic needs updated to remove deprecated functions and implement indent, but our tests for it are probably correct. With all warnings hidden, mass actions will work except for indent. Could be supported.
flexsections needs updated to remove deprecated functions and implement indent, but our tests for it are probably correct. In its current state, it breaks Moodle severely and should not be supported yet.

### CODE REVIEW

**Comment by PhMemmel** [comment]
Great work! Thank you!

For the formats we don't know yet if they support indentation or not:
Should we just remove the indentation behat test for indentation? We also could add a behat given method checking `course_get_format($COURSE->id)->uses_indentation()` so these tests are being skipped. What approach do you suggest?

**Comment by Syxton** [comment]
@PhMemmel  There are just so many unknowns when it comes to these course formats.  How many will even continue development for 4.0? How many will include indention?  Also, I believe it is up to each format to decide how to class and style the indention, so the tests could be completely different.  I based the need for indentions on the use of indentions in the 3.11 formats.  This pull makes it really easy to add tests for new formats.  It still requires us to add the format to the supported list.  I think I will leave the tests as is for now, since the formats aren't even ready for testing yet.  Then we can remove tests completely or alter the tests when we know more.  In the meantime, the extra tests aren't hurting anything.  On a related note, do we want to remove tiles and onetopic from the list of currently supported 4.0 formats?  In production with all errors/warnings hidden, it looks like they work, but the deprecation warnings cause automated testing to fail.  Are we confident that they will get updated?  So far topcoll is the only one I've tested that is fully 4.0 ready.

**Comment by PhMemmel** [comment]
I very much like the approach of just adding the tests for the format we support, so removing onetopic and tiles from the supported formats list for now might be a good idea. As soon as we see them being adopted to 4.0 we can add them again and adapt the tests (including if indentation is part of the format and how it's implemented, as the css selector which is being used in the behat test right now could theoretically also change etc.).

I tested them manually and they work in general (I even added a fallback for checkbox generation to work in tiles). However, the drag&drop for example is completely bugged for both of the formats, so they aren't *really* working in 4.0 yet.

I don't really care if we also remove the tests for them right now or leave them for the time being, you decide :-)

BTW: I just did a quick search, but have not found an example: Is it possible to make the ci install the plugins of the supported formats before running the behat tests? If so, should we do that?

**Comment by PhMemmel** [comment]
I managed to install topcoll in the ci in a test branch, see https://github.com/Syxton/moodle-block_massaction/runs/6097663586, but unfortunately, grunt is now failing because it also checks the topcoll format directory. Not sure, if this is on purpose. No idea right now, how to make grunt only run on our plugin directory in the ci

**Comment by Syxton** [comment]
@PhMemmel I would say that if our plugin works for some parts and "does no harm" on the parts that don't work, we might consider that supportable. "tiles, onetopic, grid, buttons" would fall into that "mostly working" category.  "flexsections" is too broken to be concerned about, but it wouldn't take much work to get it to the same condition as the "mostly working" group.

I figured there was a way to get ci to install required plugins, but I think the issue you mentioned plus the fact that we would have to keep track of working branches/dev branches, new forks/maintainers on a multitude of other plugins would make it a nightmare.  

I will remove the tests from the master pull request and move each "not fully working" 3rd party format test into a separate pull request so we don't lose the work that already exists and can quickly add each format back in as needed.  Also, for anyone that wants to run certain formats as is (partially working and failing tests), they can pull in the changes they want.  Give me a bit to parse it all out.

**Comment by PhMemmel** [comment]
Sounds good, I agree. Thank you for the work!

**Pull request merged**
