### PR TITLE
Draft: Huge refactoring to 311

### PR DESCRIPTION
**Pull request by PhMemmel**
This PR more or less completely rewrites this plugin to latest moodle standards being compatible with Moodle 3.11.4.

The rework has been based on the original plugin https://github.com/hqhoang/moodle-block_massaction. I "merged" current master into this to be able to send this PR.

It includes:
- Drop jquery, use pure ES6
- added some unit and behat tests
- Fix complains of codechecker
- Add "Make available" action
- Add mass cloning (including admin option to do this as background task, as cloning of activities often runs into timeouts as it's pretty load heavy to do a full backup and restore process for multiple course modules)
- Plugin is widely independent on course format/themes
- Plugin is reacting to Drag&Drop events (Drag&Drop Uploads, Renaming sections, reordering sections): Unfortunately a pretty hacky implementation, but don't think there is a better way right now

As this PR is a complete rewrite I'm marking this as draft, because I'm looking forward to discussions on this first. However, this is completely working and would be mergeable from my point of view. Thank you in advance!

### CODE REVIEW

**Comment by Syxton** [comment]
@PhMemmel This is really great work.  I have added to it (Duplicate To feature) and moved the code over to GitHub actions instead of travis.ci.  See https://github.com/Syxton/moodle-block_massaction/tree/refactored

It seems to me that this is mostly your code now.  Would you want to be the official maintainer? (assuming we can ever figure out how to get it changed)

**Comment by PhMemmel** [comment]
Hi @Syxton,

thank you very much for reviewing and enhancing/improving my PR. Looks great!

What you did there makes me realize that you are definitely more experienced in moodle coding than me (still pretty new to that), so I definitely would prefer and be thankful if you could be the official maintainer of this plugin. Of course, I'd be happy to help you with that and I'm also going to adapt the plugin for Moodle 4.0. I'd really appreciate if you could review that.

Speaking of figuring out how to become the official maintainer... Following up on what's posted [here](https://moodle.org/mod/forum/discuss.php?d=422640) (https://moodle.org/mod/forum/discuss.php?d=422640) makes me think a short "I'll do it" in this forum might be the way to go :-)

Maybe also a comment here could be helpful: https://tracker.moodle.org/browse/MDL-20213

Again, thank you very much!

**Comment by PhMemmel** [comment]
The "Notes" section in https://docs.moodle.org/dev/Plugins_adoption_programme#Initiating_forced_adoption says:
"The @author tag in the phpDocs block of a file should never be changed even after the whole file is rewritten eventually. It's GPL legal statement, not a credits line."

So is there a need to revert the phpdoc comments in `action.php` and `block_massaction.php` or maybe other files? Do you see any other problems of this type?

**Comment by Syxton** [comment]
I'll admit that I didn't pay close enough attention to the @author contents in each file, I was just trying to clear code checks.  I'll go back and see which authorship I altered inadvertently and make them correct.

**Comment by Syxton** [comment]
@PhMemmel I just pushed a commit that should return all files that had authership and copyright info back to their originals.

**Comment by PhMemmel** [comment]
Thank you very much and sorry for not doing this myself in the first place!

**Pull request closed without merging**
