### PR TITLE
Design rework with bootstrap

### PR DESCRIPTION
**Pull request by PhMemmel**
I reworked the design of the block a little bit using buttons and bootstrap classes.

grafik

While doing this I tried to reduce accessibility problems. Let's say I did everything I could there. Unfortunately, I'm no CSS and accessibility expert ;-)

@jrchamp Would you mind having a look at it? I tried to include your suggestions from https://github.com/Syxton/moodle-block_massaction/pull/28#discussion_r857700546. I also used the WAVE browser extension to solve most of the accessibility issues caused by `block_massaction`.

### CODE REVIEW

**Review by Syxton — COMMENTED** [review]
@PhMemmel I like this alot.  While I don't fully understand why it is better for a screenreader to have static English field names instead of translated, I will defer to @jrchamp on the accessbilities front.  Much cleaner code and it won't show the void(0) on mouseover anymore.  Very nice.  I'll wait to see what @jrchamp has to say.

**Comment by Syxton** [comment]
@PhMemmel Ah, after re-reading #26 I see that it isn't the screenreader that needs the static strings for field names, but the Behat tests.  Understood.

**Comment by jrchamp** [comment]
The buttons are a very nice improvement! The selects will be treated as labelled by the automated tests and the first option will visually display the label text. Looks good to go! 👍 

Additional details:
- With [`name` attributes](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#name), I typically expect the values to be programmatic (for example, `name="move_to_section"`) which helps to differentiate it from human-friendly text. If the current code is working, then there's no need to change it.
- I think a screenreader might announce the select label and the option value, which would be some duplication, but that's probably okay for now. I think the only way to avoid that would be to remove the first option that is used to visually display text and convert the select's label to a formal `<label>` tag, but I know that's not the UI design that you want.

**Comment by PhMemmel** [comment]
@jrchamp Thank you very much for the very helpful feedback!

I pushed another commit to apply your suggestion of making the `name` attributes more programmatic.

Select labels: I did some research and using aria-label seems to be a valid approach, a separate label would be better though :-) I also tried with orca screenreader. And yes, it is being announced twice now: First time as label for the select itself and another time when it is being expanded, as it is now the (first) currently selected option. I think this is understandable.

Thanks again @jrchamp!
@Syxton: Mergeable from my side

**Pull request merged**
