### PR TITLE
Cleanup before eventual release

### PR DESCRIPTION
**Pull request by PhMemmel**
I did some cleanups for a potential release after the transfer of the maintainership.

This includes:
- Adding behat and phpunit tests for "duplicate to section" feature
- Fixing name attribute of "duplicate to section" select
- Fixing ordering of modules in the "duplicate to section" feature
- Code style, improvement of comments/doc
- Removing the lang files so lang strings can be maintained via AMOS (he and fr haven't been maintained anyway in this branch)
- Bump up version

From my point of view this is somewhat releasable, I ran all the tests again and did some manual testing, looks good to me.

Some additional thoughts:
- Not sure if there is a need to change the "maturity" in `version.php`.
- Also not sure about the "requires", it's currently at 3.11.4, because I only tested this on 3.11, but probably this is compatible to lower versions, I just cannot test right now. Should at least 3.9 LTS be added to the ci automated testing?
- Maybe the Readme should be updated :-)
- Let me know if you still see some violations of general or moodle specific conventions (naming etc.). I'd be happy to adapt

### CODE REVIEW

**Comment by Syxton** [comment]
I have done some testing on 3.9 (i'll see if I can go back any further).  The only hiccup I've found so far isn't 3.9 specific, but it is that we need to check to see if allowstealth is true before we can use the "Make Available" action.  I'll keep looking, but so far the changes look pretty good to me.

On release we will set the maturity to stable.  I can add additional versions to the testing if we want to aim for 3.9-4.0

**Comment by PhMemmel** [comment]
I think targeting 3.9 (being latest LTS) would definitely be sufficient.

Let's not aim for 4.0 yet with this implementation. For 4.0, I will definitely go for another rework using the new course editor API which will be available in 4.0. This will require deep changes again, but will also simplify the code and make it more stable by a lot. So I tend to not merge both of the implementations into one branch, but have a different one for 4.0 and following versions.

**Comment by PhMemmel** [comment]
Ah, good catch. Didn't realize there is an 'allowstealth' config. Will take care of it and push it to this PR

**Comment by Syxton** [comment]
@PhMemmel So we are looking really good to add 3.9 to the next release.  I believe it will pass all checks once a single issue is worked around.  Moodle 3.9 supports PHP 7.2, and PHP 7.2 can't use array_key_first().  [https://www.php.net/manual/en/function.array-key-first.php](https://www.php.net/manual/en/function.array-key-first.php) has a polyfill for the function that could probably be used.

FILE: /home/runner/work/moodle-block_massaction/moodle-block_massaction/moodle/blocks/massaction/classes/actions.php
------------------------------------------------------------------------------------------------------------------------------------
FOUND 3 ERRORS AFFECTING 3 LINES
------------------------------------------------------------------------------------------------------------------------------------
 102 | ERROR | The function array_key_first() is not present in PHP version 7.2 or earlier
     |       | (PHPCompatibility.FunctionUse.NewFunctions.array_key_firstFound)
 103 | ERROR | The function array_key_first() is not present in PHP version 7.2 or earlier
     |       | (PHPCompatibility.FunctionUse.NewFunctions.array_key_firstFound)
 107 | ERROR | The function array_key_first() is not present in PHP version 7.2 or earlier
     |       | (PHPCompatibility.FunctionUse.NewFunctions.array_key_firstFound)

**Comment by PhMemmel** [comment]
Guess I abused `array_key_first` there anyway, so I rewrote it a better way, no need for a polyfill :-)

**Pull request merged**
